services:
  expo-app:
    build: .
    container_name: praktikum_modul3_reactnative
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19006:19006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - CI=false
    command: npx expo start --tunnel
